---
name: update-readme

on:
  pull_request:
    branches:
      - main
    paths:
      - action.yml

jobs:
  update-readme:
    uses: bendwyer/github-workflows/.github/workflows/github-action-update-readme.yml@main
    with:
      gh_app_id: ${{ vars.GH_APP_ID }}
    secrets:
      gh_app_private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}
